### ISSUE TITLE
Volume change not working

### ISSUE THREAD

**Issue by ai9-** [KillerBOSS2019/TP-YTDM-Plugin#2]
Using a button with `Volume Up by 5%` or `Volume Down by 5%` results in no action. Sometimes it also pops up a `Failed to execute script TouchPortalYTMD` error message.

It doesn't seem like log.txt has any useful info, anyways here's the relevant section:
```
09:09:43.536 - [LOG] (192.168.1.223) Received request on port 12134...
09:09:43.538 - [LOG] (192.168.1.223) Waiting for request on port 12134...
09:09:43.581 - [LOG] (192.168.1.223) Received request on port 12134...
09:09:43.583 - [LOG] (192.168.1.223) Waiting for request on port 12134...
09:09:43.584 - [LOG] (192.168.1.223) Received request on port 12134...
09:09:43.585 - [LOG] (Actions) Button State UP for index: (5, 2) on page media
09:09:43.586 - [LOG] (192.168.1.223) Waiting for request on port 12134...
09:09:43.587 - [LOG] (Actions) Doing action plugin
09:09:44.986 - [LOG] (State System) Changed state Trackcurrentdurationhuman from 3:16 to value 3:26
09:09:44.992 - [LOG] (State System) Changed state SeekBarStatus from 68 to value 72
```

**Comment by ai9-** [comment]
Oh, `Set Volume to` seems to have the same issue.

**Comment by DamienStaebler** [comment]
Yes I am aware of it, it happens everytime when u spam the button so like if you press play button 2x in less then 1-2 seconds And that is due to need to load so much data and getting the new data which they called Extra data
Another thing is that the reason why it has around 3-8s for it to display anything is due to the Server and Http request has delay as well

**Comment by ai9-** [comment]
quitting and restarting touchportal and yt media player, setting the volume to 0 manually and pressing the button once seems to indeed work. sadly if you trigger the error once it doesn't work until you restart touchportal.

**Comment by DamienStaebler** [comment]
The Reason why it sets back to 0 is because theres nothing playing, and with the error that your having is being worked on you dont need to restart TP just go to %appdata%/touchportal/plugins in there it should have a folder that is called YoutubeMusic or something just open the exe to avoid restart TP
